/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dhii
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txthasil = new javax.swing.JTextField();
        btnp = new javax.swing.JButton();
        btnm = new javax.swing.JButton();
        btnx = new javax.swing.JButton();
        btnbagi = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnce = new javax.swing.JButton();
        btnhasil = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txthasil, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnp.setText("+");
        btnp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpMouseClicked(evt);
            }
        });
        getContentPane().add(btnp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, 73));

        btnm.setText("-");
        btnm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmMouseClicked(evt);
            }
        });
        getContentPane().add(btnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 41, 70));

        btnx.setText("x");
        btnx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnxMouseClicked(evt);
            }
        });
        getContentPane().add(btnx, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 41, 72));

        btnbagi.setText("/");
        btnbagi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbagiMouseClicked(evt);
            }
        });
        getContentPane().add(btnbagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 41, 69));

        btn3.setText("3");
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 81, 84, 92));

        btn6.setText("6");
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 179, 84, 92));

        btn9.setText("9");
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 277, 84, 104));

        btnce.setText("CE");
        btnce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnceMouseClicked(evt);
            }
        });
        getContentPane().add(btnce, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 90, -1, 104));

        btnhasil.setText("=");
        btnhasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhasilMouseClicked(evt);
            }
        });
        getContentPane().add(btnhasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, -1, 104));

        btn2.setText("2");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 81, 96, 92));

        btn5.setText("5");
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 179, 96, 92));

        btn8.setText("8");
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 277, 96, 103));

        btn0.setText("0");
        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn0MouseClicked(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 387, 96, 96));

        btn1.setText("1");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 81, 87, 92));

        btn4.setText("4");
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 179, 87, 92));

        btn7.setText("7");
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 281, 87, 99));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        // TODO add your handling code here:
              String res = txthasil.getText();
        if(txthasil.getText().isEmpty())
            txthasil.setText("1");
        else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/"))
        {
            txthasil.setText(txthasil.getText() + "1");
            value2 = Integer.parseInt(value2 + "1");
        }
        else
            txthasil.setText(txthasil.getText()+ "1");
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        // TODO add your handling code here:
        String res = txthasil.getText();
      if(txthasil.getText().isEmpty())
            txthasil.setText("2");
       else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/"))
        {
            txthasil.setText(txthasil.getText() + "2");
            value2 = Integer.parseInt(value2 + "2");
        }
        else
            txthasil.setText(txthasil.getText()+ "1");
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        // TODO add your handling code here:
          String res = txthasil.getText();
      if(txthasil.getText().isEmpty())
            txthasil.setText("3");
       else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/"))
        {
            txthasil.setText(txthasil.getText() + "3");
            value2 = Integer.parseInt(value2 + "3");
        }
        else
            txthasil.setText(txthasil.getText()+ "3");
    }//GEN-LAST:event_btn3MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        // TODO add your handling code here:
           String res = txthasil.getText();
      if(txthasil.getText().isEmpty())
            txthasil.setText("4");
       else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/"))
        {
            txthasil.setText(txthasil.getText() + "4");
            value2 = Integer.parseInt(value2 + "4");
        }
        else
            txthasil.setText(txthasil.getText()+ "4");
    }//GEN-LAST:event_btn4MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        // TODO add your handling code here:
          String res = txthasil.getText();
      if(txthasil.getText().isEmpty())
            txthasil.setText("5");
       else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/"))
        {
            txthasil.setText(txthasil.getText() + "5");
            value2 = Integer.parseInt(value2 + "5");
        }
        else
            txthasil.setText(txthasil.getText()+ "5");
    }//GEN-LAST:event_btn5MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        // TODO add your handling code here:
            String res = txthasil.getText();
      if(txthasil.getText().isEmpty())
            txthasil.setText("6");
       else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/"))
        {
            txthasil.setText(txthasil.getText() + "6");
            value2 = Integer.parseInt(value2 + "6");
        }
        else
            txthasil.setText(txthasil.getText()+ "6");
    }//GEN-LAST:event_btn6MouseClicked

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        // TODO add your handling code here:
            String res = txthasil.getText();
      if(txthasil.getText().isEmpty())
            txthasil.setText("7");
       else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/"))
        {
            txthasil.setText(txthasil.getText() + "7");
            value2 = Integer.parseInt(value2 + "7");
        }
        else
            txthasil.setText(txthasil.getText()+ "7");
    }//GEN-LAST:event_btn7MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        // TODO add your handling code here:
        String res = txthasil.getText();
      if(txthasil.getText().isEmpty())
            txthasil.setText("8");
       else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/"))
        {
            txthasil.setText(txthasil.getText() + "8");
            value2 = Integer.parseInt(value2 + "8");
        }
        else
            txthasil.setText(txthasil.getText()+ "8");
    }//GEN-LAST:event_btn8MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        // TODO add your handling code here:
           String res = txthasil.getText();
      if(txthasil.getText().isEmpty())
            txthasil.setText("9");
       else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/"))
        {
            txthasil.setText(txthasil.getText() + "9");
            value2 = Integer.parseInt(value2 + "9");
        }
        else
            txthasil.setText(txthasil.getText()+ "9");
    }//GEN-LAST:event_btn9MouseClicked

    private void btn0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseClicked
        // TODO add your handling code here:
            String res = txthasil.getText();
      if(txthasil.getText().isEmpty())
            txthasil.setText("0");
       else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/"))
        {
            txthasil.setText(txthasil.getText() + "0");
            value2 = Integer.parseInt(value2 + "0");
        }
        else
            txthasil.setText(txthasil.getText()+ "0");
    }//GEN-LAST:event_btn0MouseClicked

    private void btnceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnceMouseClicked
        // TODO add your handling code here:
        txthasil.setText("");
    }//GEN-LAST:event_btnceMouseClicked

    private void btnpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpMouseClicked
        // TODO add your handling code here:
          if(txthasil.getText().isEmpty())
           return;
        else
            value1 = Integer.parseInt(txthasil.getText());
            txthasil.setText( txthasil.getText() + " " + btnp.getText() );
            operator = "plus";
    }//GEN-LAST:event_btnpMouseClicked

    private void btnmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmMouseClicked
        // TODO add your handling code here:
         if(txthasil.getText().isEmpty())
           return;
        else
            value1 = Integer.parseInt(txthasil.getText());
            txthasil.setText( txthasil.getText() + " " + btnm.getText() );
            operator = "minus";
    }//GEN-LAST:event_btnmMouseClicked

    private void btnbagiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbagiMouseClicked
        // TODO add your handling code here:
        if(txthasil.getText().isEmpty())
           return;
        else
            value1 = Integer.parseInt(txthasil.getText());
            txthasil.setText( txthasil.getText() + " " + btnbagi.getText() );
            operator = "division";
    }//GEN-LAST:event_btnbagiMouseClicked

    private void btnxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnxMouseClicked
        // TODO add your handling code here:
         if(txthasil.getText().isEmpty())
           return;
        else
            value1 = Integer.parseInt(txthasil.getText());
            txthasil.setText( txthasil.getText() + " " + btnx.getText() );
            operator = "multiplication";
    }//GEN-LAST:event_btnxMouseClicked

    private void btnhasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhasilMouseClicked
        // TODO add your handling code here:
                double answer = 0;
         if(operator == "plus")
             answer = value1 + value2;
         else if(operator=="minus")
              answer = value1 - value2;
         else if (operator =="multiplication")
             answer = value1 * value2;
         else if(operator == "division")
             answer = value1/value2;
        
         String Result = Double.toString(answer);
         txthasil.setText(Result);
    }//GEN-LAST:event_btnhasilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }
    static int value1;
static int value2;
static String operator;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnbagi;
    private javax.swing.JButton btnce;
    private javax.swing.JButton btnhasil;
    private javax.swing.JButton btnm;
    private javax.swing.JButton btnp;
    private javax.swing.JButton btnx;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txthasil;
    // End of variables declaration//GEN-END:variables
}
